# Generated by Django 4.0.3 on 2022-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_id_profile_desc_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(max_length=250),
        ),
    ]
